# Mysql Setting

# default: &default
#   adapter: mysql2
#   #encoding: unicode
#   pool: 5
#   username: root
#   password: 
#   host: localhost

# development:
#   <<: *default
#   database: miner_development

# test:
#   <<: *default
#   database: miner_test

# production:
#   <<: *default
#   database: miner_production

#Postgres Setting

default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: postgres
  host: localhost

development:
  <<: *default
  database: miner_development

test:
  <<: *default
  database: miner_test

production:
  <<: *default
  database: miner_production