consumer_key: 				"paJP7dSVwHFwtQb6d8VOWk4qO"
consumer_secret:     	"eQ5aUrFhOwEfO8QPq0dZmi6AyS1awqEFp2SjE19i08rBvZX160"
access_token: 				"2566411526-Ul7McFY9oHRRwWXgfTycOeuBdmIM0KbgwUKfiiY"
access_token_secret: 	"bqAetskuhQ398Gru0PuUYV4C2zPgeF8tFNgx47Js9wYCl"